# XXX: there's no nighly
image: fpco/stack-build:lts

pipelines:
  default:
    - step:
        script:
          - stack upgrade
          - /root/.local/bin/stack setup --resolver nightly
          - /root/.local/bin/stack build --resolver nightly --pedantic --test
