#resolver: lts-7.24
#resolver: lts-8.24
#resolver: lts-9.17
#resolver: lts-10.9
#resolver: lts-11.0
#resolver: nightly-2020-03-10
resolver: lts-16.0

packages:
- soap/
- soap-openssl/
- soap-tls/
# - ../xml-conduit-writer

allow-newer: true

extra-deps:
- xml-conduit-writer-0.1.1.2
