#resolver: lts-5.18
#resolver: lts-6.35
#resolver: lts-7.24
#resolver: lts-8.24
#resolver: lts-9.17
resolver: nightly-2017-12-10

packages:
- soap/
- soap-openssl/
- soap-tls/
# - ../xml-conduit-writer
